version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mangues-backend-prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - mangues-network
    restart: always

  # Frontend React (Build estático)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    container_name: mangues-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mangues-network
    restart: always

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: mangues-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mangues-network
    restart: always

networks:
  mangues-network:
    driver: bridge